// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVRI0MUjgj6AEduoZmTHGR2MxWr-kz6fE',
    appId: '1:215229729191:web:e6bbd33f342686731f4e82',
    messagingSenderId: '215229729191',
    projectId: 'quiz-app-ziyad',
    authDomain: 'quiz-app-ziyad.firebaseapp.com',
    storageBucket: 'quiz-app-ziyad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoa2NfQ0rwHoo-gOoQU16aZMzWX2xhqas',
    appId: '1:215229729191:android:d4adc5c57131af021f4e82',
    messagingSenderId: '215229729191',
    projectId: 'quiz-app-ziyad',
    storageBucket: 'quiz-app-ziyad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIfE7SlrcrNDGdktgk06U6qw1bjyLHEjQ',
    appId: '1:215229729191:ios:1f4120b9863b79101f4e82',
    messagingSenderId: '215229729191',
    projectId: 'quiz-app-ziyad',
    storageBucket: 'quiz-app-ziyad.appspot.com',
    iosClientId: '215229729191-ecmhmg8j2lfbtsvu6msfj8h4em10eu1b.apps.googleusercontent.com',
    iosBundleId: 'com.ziyad.quizAppZiyad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIfE7SlrcrNDGdktgk06U6qw1bjyLHEjQ',
    appId: '1:215229729191:ios:1f4120b9863b79101f4e82',
    messagingSenderId: '215229729191',
    projectId: 'quiz-app-ziyad',
    storageBucket: 'quiz-app-ziyad.appspot.com',
    iosClientId: '215229729191-ecmhmg8j2lfbtsvu6msfj8h4em10eu1b.apps.googleusercontent.com',
    iosBundleId: 'com.ziyad.quizAppZiyad',
  );
}
